### ISSUE TITLE
Bug @russoz

### ISSUE THREAD

**Issue by EinDev** [EinDev/GithubIsNotAMessengertButIDontCare#1]

**Comment by russoz** [comment]
Hi @EinDev I absolutely loved the repo's name here.

I had recently create a GH project to hold ansible-related repos, I migrated the repos over there and clearly I forgot to enable the issues on the new andebox repo.

That said, I believe there is something odd in your setup, because andebox simply calls ansible-test and what we are getting is a permission denied from ansible-test itself.
